language: php
php:
  - 7.0

before_script:
  - composer selfupdate
  - composer install --prefer-source --dev
  - phpenv rehash

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
